# Generated by Django 2.1.9 on 2019-07-28 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reg_Data', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('Hotel_ID', models.CharField(max_length=100)),
                ('Hotel_Name', models.CharField(max_length=200)),
                ('Hotel_Address', models.TextField()),
                ('Hotel_Contact', models.CharField(max_length=50)),
                ('Hotel_Email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'HotelInfo',
            },
        ),
    ]
