# Generated by Django 2.2.2 on 2019-07-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_categoryinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecorationTypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hotel_ID', models.CharField(max_length=100)),
                ('Decoration_Key', models.CharField(max_length=100)),
                ('Decoration_Value', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'DecorationTypeInfo',
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'EventCategory',
            },
        ),
        migrations.CreateModel(
            name='FacilityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hotel_ID', models.CharField(max_length=100)),
                ('Stage', models.CharField(max_length=10)),
                ('DJ', models.CharField(max_length=10)),
                ('Pool', models.CharField(max_length=10)),
                ('Seating_Style', models.CharField(max_length=50)),
                ('Caterer', models.CharField(max_length=10)),
                ('Rental_Charge', models.CharField(max_length=10)),
                ('Decoration_Included', models.CharField(max_length=10)),
                ('Rooms', models.CharField(max_length=10)),
                ('Rooms_Type', models.CharField(max_length=10)),
                ('Other_Terms', models.TextField()),
            ],
            options={
                'db_table': 'FacilityInfo',
            },
        ),
        migrations.RenameField(
            model_name='hotelinfo',
            old_name='Hotel_Contact',
            new_name='Hotel_Category',
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='Hotel_Area',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='Hotel_City',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='Hotel_Event_Type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='Hotel_Max_Gathering',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='Hotel_Min_Gathering',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='Hotel_Phone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='Hotel_PriceType',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='Hotel_State',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='Status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
