# Generated by Django 2.2.2 on 2019-07-31 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190729_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decorationtypeinfo',
            old_name='Decoration_Key',
            new_name='Decoration_Name',
        ),
        migrations.RenameField(
            model_name='decorationtypeinfo',
            old_name='Decoration_Value',
            new_name='Decoration_Price',
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='Hotel_Price',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
