# Generated by Django 2.2.2 on 2019-07-31 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190731_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilityinfo',
            old_name='Rooms',
            new_name='AC_Rooms',
        ),
        migrations.RenameField(
            model_name='facilityinfo',
            old_name='Rooms_Type',
            new_name='NON_AC_Rooms',
        ),
    ]
