# Generated by Django 2.2.2 on 2019-07-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190731_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelinfo',
            old_name='Reg_Data',
            new_name='Reg_Date',
        ),
        migrations.AddField(
            model_name='facilityinfo',
            name='Crokery_Included',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facilityinfo',
            name='Hall_Included',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
