# Generated by Django 2.2.2 on 2019-08-04 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190804_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgdata',
            name='Hotel_ID',
        ),
        migrations.AlterModelTable(
            name='imgdata',
            table='DATA',
        ),
    ]
