# Generated by Django 2.2.2 on 2019-08-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190804_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgdata',
            name='Hotel_ID',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
