# Generated by Django 2.2.2 on 2019-08-04 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_imgdata_hotel_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imgdata',
            table='ImageData',
        ),
    ]
