# Generated by Django 2.2.2 on 2019-08-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190804_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgdata',
            name='Image_Type',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
